#Configuration file for the "pre-commit" linting/formatting tool.

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        files: lib
        args: ["--rcfile=lib/test/pylintrc"]
#End of file.
