name: Python linting and formatting

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  #This job is designed to run tests on all source-code files
  #modified by the Pull Request (PR).  This is done by running
  #a master python script which collects all modified files,
  #and then passing those files off to additional scripts
  #to run the actual tests.
  source_code_tests:
    runs-on: ubuntu-latest
    steps:
    # acquire github action routines
    - uses: actions/checkout@v2
    # acquire specific version of python
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: '3.8' # Semantic version range syntax or exact version of a Python version
    # install required python packages
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Install latest version of PIP
        pip install PyGithub                 # Install PyGithub python package
        pip install pylint                   # Insteall Pylint python package
    # run CAM source code testing master script:
    - name: source-code testing python script
      env:
        PR_NUMBER: ${{ github.event.number }}
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: .github/scripts/pr_mod_file_tests.py --access_token $ACCESS_TOKEN --pr_num $PR_NUMBER --rcfile test/.pylintrc --pylint_level 9.5

