name: pull request close actions workflow

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # acquire github action routines
    - uses: actions/checkout@v2
    # acquire specific version of python
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: '3.6' # Semantic version range syntax or exact version of a Python version
    # install required python packages
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Install latest version of PIP
        pip install PyGithub                 # Install PyGithub pythong package
    # run CAM pr-closing scripts
    - name: python action scripts
      env:
        TEST_VAR: 'Goodbye_World!'
      run: python .github/scripts/ghub_actions_sandbox.py --test_env $TEST_VAR

